config/routes.rb
Rails.application.routes.draw do
  root to: 'contents#home'

  put :like,    to: 'contents#like',    path: 'content/:id/like'
  put :dislike, to: 'contents#dislike', path: 'content/:id/dislike'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def home
    # this is our "database"
  end

  def like
    update_vote(true)
  end

  def dislike
    update_vote(false)
  end

private

  def update_vote(value)
    id = params[:id]
    cookies["vote-#{id}"] = value

    if request.xhr?
      render json: { count: Time.current.to_i, id: id }
    else
      redirect_to :root
    end
  end

end

app/views/contents/home.html.erb
<h1>Home</h1>

<ul>
  <%- 10.times do |id| -%>
    <li>
      <strong class="votes-count" data-id="<%= id %>"><%= Time.current.to_i + rand(-10000..10000)%></strong>
      users liked this.

      <%- if cookies["vote-#{id}"] -%>
        <%= link_to "Dislike", dislike_path(id: id), class: 'vote', method: :put, remote: true, data: { toggle_text: 'Like', toggle_href: like_path(id: id), id: id } %>
      <%- else -%>
        <%= link_to "Like", like_path(id: id), class: 'vote', method: :put, remote: true, data: { toggle_text: 'Dislike', toggle_href: dislike_path(id: id), id: id } %>
      <%- end -%>
    </li>
  <%- end -%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxTest</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>